### ISSUE TITLE
SVG Placeholder

### ISSUE THREAD

**Issue by stephanfriedrich** [OpenSourceWorkflow/generator-kickstart#172]
Ahoi, 
in our Projects, there are some inline SVG's in our HTML-Templates.
It would be nice if kickstart provide a placeholder, which inserts SVG's from our SVG-Asset-Files.

Today, CMS/Backend/Frontend developer have to update these inline SVG manually, if the SVG File changed. 

What do you think? Hopefully you could understand what i mean.

**Comment by markusfalk** [comment]
Could you provide an example please? :)

**Comment by SpikeShape** [comment]
My idea would be to add a default sub folder where inline SVGs are stored just like the components. SVG files could be loaded by typing something like 
```
{svg:{map}}
```

This way the svg/map.svg file could be used in multiple places without having to edit multiple places if the SVG file needs to be changed.

I'd appreciate such a feature, too.

**Comment by stephanfriedrich** [comment]
correct, my intention was to use the same svg in multiple html files.

**Comment by markusfalk** [comment]
Why are you not just adding the svg to an existing compontent and use that whereever you want?

**Comment by stephanfriedrich** [comment]
hehe ..... awesome idea... 
BUUUUUT then we need an placeholder replacement not only for level0 (index.html), also for level1.

BTW.: Da war doch mal einer der hatte da so ne Ähnliche Idee ;)

**Comment by markusfalk** [comment]
buuuut right now kickstar does not support nesting, does it? :D

**Comment by stephanfriedrich** [comment]
yes, not yet. BUUT we can build this ?! .... :dancers:

**Comment by markusfalk** [comment]
until then ;)
