### ISSUE TITLE
jquery path error without installed bower

### ISSUE THREAD

**Issue by stephanfriedrich** [OpenSourceWorkflow/generator-kickstart#174]
i create an new project with kickstart, but npm package bower is not installed lokal.
so kickstart generate files/folders and run "npm install", but wont clone e.g. jquery.

unfortunately, it inserts jquery lib path into requirejs.config

is this expected behaviour?

hope you understand what i described. sorry for my english. ;)

**Comment by markusfalk** [comment]
Are you talking about the globally installed bower? That is a requirement for kickstart so it assumes that this is already there. if not the install of jquery fails. 

If bower is installed you can also run ```bower install``` yourself

**Comment by stephanfriedrich** [comment]
ah i see bower is a requirement.
thx for your fast response.

have a nice day
